package frontendpages;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author EISHA
 */
import BackEND.Appointment;
import BackEND.Doctor;
import BackEND.ReceiptPrint;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class GenerateReceipt extends javax.swing.JFrame {
double bHeight=0.0;
 String pat_id;
  String App_id;
   String Recp_id;
    String Recpt_id;
      int room_no;
       String pay_status;
   
    /**
     * Creates new form GenerateReceipt
     */
    public GenerateReceipt() {
        initComponents();
        loadPaidAppointmentIds();
        loadRoomNo();
    }
 public void loadRoomNo(){
        // Get the selected Appointment ID
        String selectedAppointmentId = (String) app_id.getSelectedItem();
        String selectedPatientId = (String) patient_id.getSelectedItem(); // Assuming patient_id is also a JComboBox

        if (selectedAppointmentId != null && selectedPatientId != null &&
            !selectedAppointmentId.trim().isEmpty() && !selectedPatientId.trim().isEmpty()) {

            // Fetch the Doctor Room Number
            Doctor doc4=new Doctor();
            
            String docRoomNo = doc4.getDoctorRoomNumber(selectedAppointmentId, selectedPatientId);

            if (docRoomNo != null) {
                // Display the Doctor Room Number
                doc_room.removeAllItems();
                doc_room.addItem(docRoomNo);
                doc_room.setSelectedItem(docRoomNo);
            } else {
                JOptionPane.showMessageDialog(null, "No Doctor Room Number found for the selected Appointment and Patient ID.", "Information", JOptionPane.INFORMATION_MESSAGE);
                doc_room.removeAllItems();
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        recep_id = new javax.swing.JTextField();
        recepsionist_id = new javax.swing.JTextField();
        doc_room = new javax.swing.JComboBox<>();
        peint_recep = new javax.swing.JButton();
        app_id = new javax.swing.JComboBox<>();
        patient_id = new javax.swing.JComboBox<>();
        payStatus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backbtn.setText("<-");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Generate Receipt");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Appointment Id:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Receipt Id:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Patient Id:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Doctor Room no:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Pay Status:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Receptionist Id:");

        doc_room.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        peint_recep.setBackground(new java.awt.Color(255, 255, 204));
        peint_recep.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        peint_recep.setText("Print Receipt");
        peint_recep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peint_recepActionPerformed(evt);
            }
        });

        app_id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        app_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                app_idActionPerformed(evt);
            }
        });

        patient_id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        payStatus.setText("Paid");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(recep_id, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(app_id, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patient_id, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(recepsionist_id, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doc_room, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(payStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backbtn)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(peint_recep, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(backbtn))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doc_room, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(app_id, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(recep_id, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(payStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(recepsionist_id, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patient_id, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(peint_recep)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        new ReceptionistDashBoard().setVisible(true);
    }//GEN-LAST:event_backbtnActionPerformed
public void loadPaidAppointmentIds() {
    try {
        // Create an instance of the class containing the getPaidAppointmentList method
        Appointment appointment = new Appointment();
        ArrayList<String> paidAppointmentIds = appointment.getPaidAppointmentList();

        // Clear existing items in the JComboBox
        app_id.removeAllItems();

        // Populate the JComboBox with paid appointment IDs
        for (String appointmentId : paidAppointmentIds) {
            app_id.addItem(appointmentId);
        }
    } catch (HeadlessException e) {
        JOptionPane.showMessageDialog(this, "Error loading paid appointment IDs: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
   
    }
}

    private void peint_recepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peint_recepActionPerformed
        // TODO add your handling code here:
         pat_id=patient_id.getSelectedItem().toString();
           
     App_id=(String) app_id.getSelectedItem();
       Recp_id=recep_id.getText();
      Recpt_id=recepsionist_id.getText();
     room_no = Integer.parseInt(doc_room.getSelectedItem().toString());

     if(Recp_id.isEmpty()){
          JOptionPane.showMessageDialog(null, "Receipt id is mandatory: ");
   
     }
     else{
       ReceiptPrint pri=new ReceiptPrint(App_id,pat_id,Recp_id,Recpt_id,room_no);
       pri.AddtoDb();
     }
     
                 bHeight = (double) App_id.length();
                 JOptionPane.showMessageDialog(rootPane, bHeight);
                 PrinterJob pj=PrinterJob.getPrinterJob();
                 pj.setPrintable(new BillPrintable(),getPageFormat(pj));
                 try{
                     pj.print();
                 }
                 catch(PrinterException ex){
                     ex.printStackTrace();
                 }
    }//GEN-LAST:event_peint_recepActionPerformed

    private void app_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_app_idActionPerformed
        // TODO add your handling code here:
        
        // Get the selected Appointment ID
        String selectedAppointmentId = (String) app_id.getSelectedItem();

        if (selectedAppointmentId != null && !selectedAppointmentId.trim().isEmpty()) {
            Appointment app2=new Appointment();
            // Fetch the Patient ID for the selected Appointment ID
            String patientId = app2.getPatientIdByAppointmentId(selectedAppointmentId);

            if (patientId != null) {
                // Clear existing items in the Patient ID JComboBox
                patient_id.removeAllItems();

                // Add the fetched Patient ID to the JComboBox
                patient_id.addItem(patientId);

                // Optionally, set it as the selected item
                patient_id.setSelectedItem(patientId);
// Example: Display in a JLabel
            } else {
                // Handle case where no Patient ID is found
                JOptionPane.showMessageDialog(null, "No Patient ID found for the selected Appointment ID.", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    

    }//GEN-LAST:event_app_idActionPerformed

    public PageFormat getPageFormat(PrinterJob pj){
        PageFormat pf=pj.defaultPage();
        Paper paper=pf.getPaper();
        
        double bodyHeight=bHeight;
        double headerHeight=5.0;
        double footerHeight=5.0;
        double width=cm_to_pp(8);
        double height=cm_to_pp(headerHeight+bodyHeight+footerHeight);
        paper.setSize(width,height);
        paper.setImageableArea(0,10,width, height-cm_to_pp(1));
        
        pf.setOrientation(PageFormat.PORTRAIT);
        pf.setPaper(paper);
        return pf;
        
    }
    public static double cm_to_pp(double cm){
        return toPPI(cm*0.393600787);
        
    }
    public static double toPPI(double inch){
        return inch*72d;
    }
//    public PageFormat getPageFormat(PrinterJob pj) {
//    PageFormat pf = pj.defaultPage();
//    Paper paper = pf.getPaper();
//
//    // Define fixed dimensions for a medium-sized receipt
//    double receiptWidth = cm_to_pp(8);  // Width of the receipt in cm (e.g., 8cm)
//    double receiptHeight = cm_to_pp(20); // Height of the receipt in cm (e.g., 20cm)
//
//    paper.setSize(receiptWidth, receiptHeight);
//    paper.setImageableArea(10, 10, receiptWidth - 20, receiptHeight - 20); // Margins
//
//    pf.setOrientation(PageFormat.PORTRAIT);
//    pf.setPaper(paper);
//    return pf;
//}

   public class BillPrintable implements Printable {

    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex)
            throws PrinterException {

        int result = NO_SUCH_PAGE;

        if (pageIndex == 0) {
            Graphics2D g2d = (Graphics2D) graphics;
            g2d.translate((int) pageFormat.getImageableX(), (int) pageFormat.getImageableY());

            // Header and Clinic Details
            try {
                int y = 20;
                int yShift = 10;
                int headerRectHeight = 15;

                g2d.setFont(new Font("Monospaced", Font.PLAIN, 10));
                g2d.drawImage(new ImageIcon("D:\\4semester\\final-sems-pro-SC\\src\\main\\java\\applogo.jpg").getImage(), 50, 20, 90, 30, rootPane);
                y += yShift + 30;
                g2d.drawString("--------------------------", 12, y);
                y += yShift;
                g2d.drawString("Clinic Management System", 12, y);
                y += yShift;
                g2d.drawString("Address: Rawalpindi, Pakistan", 12, y);
                y += yShift;
                g2d.drawString("Phone: +92300000000", 12, y);
                y += yShift;
                g2d.drawString("Email: contact:eishasajid316@gmail.com", 12, y);
                y += yShift;
                g2d.drawString("--------------------------", 12, y);
                y += headerRectHeight;

                // Display IDs in the Header
                g2d.drawString("Patient ID: " + pat_id, 10, y);
                y += yShift;
                g2d.drawString("Appointment ID: " + App_id, 10, y);
                y += yShift;
                g2d.drawString("Receipt ID: " + Recpt_id, 10, y);
                y += yShift;
                g2d.drawString("Receptionist ID: " + Recp_id, 10, y);
                y += yShift;
                g2d.drawString("Doctor Room No: " + room_no, 10, y);
                y += yShift;
                g2d.drawString("Payment Status: " + pay_status, 10, y);
                y += yShift;
                g2d.drawString("--------------------------", 10, y);
                y += headerRectHeight;

                // Leave Body Empty for Doctor's Prescription
              

                // Footer
                g2d.drawString("--------------------------", 10, y);
                y += yShift;
                g2d.drawString("THANK YOU!", 10, y);
                y += yShift;
                g2d.drawString("Software by E & A", 10, y);
                y += yShift;

            } catch (Exception e) {
                e.printStackTrace();
            }

            result = PAGE_EXISTS;
        }
        return result;
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerateReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerateReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerateReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerateReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerateReceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> app_id;
    private javax.swing.JButton backbtn;
    private javax.swing.JComboBox<String> doc_room;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox<String> patient_id;
    private javax.swing.JTextField payStatus;
    private javax.swing.JButton peint_recep;
    private javax.swing.JTextField recep_id;
    private javax.swing.JTextField recepsionist_id;
    // End of variables declaration//GEN-END:variables
}
