package frontendpages;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author EISHA
 */
import BackEND.Receptionist;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class ManageReceptionist extends javax.swing.JFrame {

    String name, email, role, shift, id, pasword, confpassword, phone;
    long num;
   

    /**
     * Creates new form RegisterForm
     */
    public ManageReceptionist() {
        initComponents();
        scaleImage();
    }
     public void scaleImage() {
        ImageIcon icon = new ImageIcon("C:\\Users\\EISHA\\Desktop\\patientbackk.jpeg");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(back_img_label.getWidth(), back_img_label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        back_img_label.setIcon(scaledIcon);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rec_conf_pass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        rec_pass = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        rec_email = new javax.swing.JTextField();
        rec_phone = new javax.swing.JTextField();
        rec_role = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        BACKbtn = new javax.swing.JButton();
        deleteRecep = new javax.swing.JButton();
        Search_rec = new javax.swing.JButton();
        update_rec = new javax.swing.JButton();
        rec_id = new javax.swing.JTextField();
        rec_name = new javax.swing.JTextField();
        rec_shift = new javax.swing.JTextField();
        searchAll = new javax.swing.JButton();
        back_img_label = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("REGISTER RECEPTIONIST");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 5, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Name:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 85, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Shift:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 85, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Receptionist id:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 204));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 197, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Confirm Password:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, -1, -1));
        jPanel1.add(rec_conf_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 130, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Password:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));
        jPanel1.add(rec_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 130, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Email:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        rec_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rec_emailActionPerformed(evt);
            }
        });
        jPanel1.add(rec_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 130, 30));
        jPanel1.add(rec_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 130, 30));
        jPanel1.add(rec_role, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 130, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Role:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Phone no:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        register.setBackground(new java.awt.Color(255, 255, 204));
        register.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        jPanel1.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 130, 30));

        BACKbtn.setBackground(new java.awt.Color(255, 51, 51));
        BACKbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BACKbtn.setText("<-");
        BACKbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKbtnActionPerformed(evt);
            }
        });
        jPanel1.add(BACKbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 5, -1, -1));

        deleteRecep.setBackground(new java.awt.Color(255, 255, 204));
        deleteRecep.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteRecep.setText("Delete");
        deleteRecep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRecepActionPerformed(evt);
            }
        });
        jPanel1.add(deleteRecep, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 130, 30));

        Search_rec.setBackground(new java.awt.Color(255, 255, 204));
        Search_rec.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Search_rec.setText("Search");
        Search_rec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_recActionPerformed(evt);
            }
        });
        jPanel1.add(Search_rec, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 130, 30));

        update_rec.setBackground(new java.awt.Color(255, 255, 204));
        update_rec.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        update_rec.setText("Update");
        update_rec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_recActionPerformed(evt);
            }
        });
        jPanel1.add(update_rec, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 130, 30));
        jPanel1.add(rec_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 130, 30));
        jPanel1.add(rec_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 111, 130, 30));
        jPanel1.add(rec_shift, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 130, 30));

        searchAll.setBackground(new java.awt.Color(204, 204, 204));
        searchAll.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchAll.setText("SEARCH All");
        searchAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAllActionPerformed(evt);
            }
        });
        jPanel1.add(searchAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 300, -1));
        jPanel1.add(back_img_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 700, 490));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 490));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 204));
        jLabel10.setText("Name");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void update_recActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_recActionPerformed
        // TODO add your handling code here:
           getValues();
        
       
        if (isValidInputs()) {
            Receptionist recep1=new Receptionist(id,name,shift,email,role,num,pasword);
           recep1.Update();
            ClearFields();
    }//GEN-LAST:event_update_recActionPerformed
    }
    private void Search_recActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_recActionPerformed
        // TODO add your handling code here:
        String id1=rec_id.getText();
        if(id1.isEmpty()){
            JOptionPane.showMessageDialog(null,"ID is required for single search");
        }
        else{
            Receptionist r=new Receptionist();
            r.Search(id1);
             ClearFields();
        }
    }//GEN-LAST:event_Search_recActionPerformed

    private void deleteRecepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRecepActionPerformed
        // TODO add your handling code here:
          String id2=rec_id.getText();
        if(id2.isEmpty()){
            JOptionPane.showMessageDialog(null,"ID is required for single search");
        }
        else{
            Receptionist res=new Receptionist();
            res.Delete(id2);
             ClearFields();
        }
    }//GEN-LAST:event_deleteRecepActionPerformed

    private void BACKbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKbtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AdminInterface().setVisible(true);
    }//GEN-LAST:event_BACKbtnActionPerformed
 public boolean isValidInputs() {
    // Check if any field is empty
    if (name.isEmpty() || email.isEmpty() || id.isEmpty() || role.isEmpty() || phone.isEmpty() || pasword.isEmpty() || confpassword.isEmpty() || shift.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please fill in all fields.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    // Check if the role is "Receptionist"
    if (!role.equalsIgnoreCase("receptionist")) {
        JOptionPane.showMessageDialog(null, "Role must be Receptionist", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    // Validate phone number
    try {
        num = Long.parseLong(phone);
        if (phone.length() != 11) {
            JOptionPane.showMessageDialog(null, "Phone number must be 11 digits.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Phone number must contain only digits.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    // Validate email format using regex
    if (!email.matches("^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$")) {
        JOptionPane.showMessageDialog(null, "Invalid email format.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    // Check if password and confirm password match
    if (!pasword.equals(confpassword)) {
        JOptionPane.showMessageDialog(null, "Password and confirm password do not match.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    // Validate shift field (it should be "morning", "evening", or "night")
    if (!(shift.equalsIgnoreCase("morning") || shift.equalsIgnoreCase("evening") || shift.equalsIgnoreCase("night"))) {
        JOptionPane.showMessageDialog(null, "Shift must be 'morning', 'evening', or 'night'.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    return true; // All validations passed
}

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed

       getValues();
        
       
        if (isValidInputs()) {
            Receptionist recep=new Receptionist(id,name,shift,email,role,num,pasword);
           
            recep.Add();
            ClearFields();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_registerActionPerformed

    private void rec_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rec_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rec_emailActionPerformed

    private void searchAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAllActionPerformed
        // TODO add your handling code here:
          Receptionist ra=new Receptionist();
            ra.SearchAll();
        
    }//GEN-LAST:event_searchAllActionPerformed
public void getValues(){
        name=rec_name.getText();
              email=rec_email.getText();
           role=rec_role.getText();
          phone=rec_phone.getText();
         num   = 0;
         shift=rec_shift.getText();
         id=rec_id.getText();
         
     
            pasword = new String(rec_pass.getPassword());
 confpassword = new String(rec_conf_pass.getPassword());
            
}
public void ClearFields(){
    rec_name.setText("");
    rec_email.setText("");
    rec_role.setText("");
    rec_phone.setText("");
    rec_id.setText("");
    rec_shift.setText("");
    rec_pass.setText("");
    rec_conf_pass.setText("");
    
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageReceptionist.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageReceptionist.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageReceptionist.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageReceptionist.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageReceptionist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACKbtn;
    private javax.swing.JButton Search_rec;
    private javax.swing.JLabel back_img_label;
    private javax.swing.JButton deleteRecep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField rec_conf_pass;
    private javax.swing.JTextField rec_email;
    private javax.swing.JTextField rec_id;
    private javax.swing.JTextField rec_name;
    private javax.swing.JPasswordField rec_pass;
    private javax.swing.JTextField rec_phone;
    private javax.swing.JTextField rec_role;
    private javax.swing.JTextField rec_shift;
    private javax.swing.JButton register;
    private javax.swing.JButton searchAll;
    private javax.swing.JButton update_rec;
    // End of variables declaration//GEN-END:variables
}
