/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author EISHA
 */
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class GenerateReceipt extends javax.swing.JFrame {
double bHeight=0.0;
 String pat_id;
  String App_id;
   String Recp_id;
    String Recpt_id;
      int room_no;
       String pay_status;
   
    /**
     * Creates new form GenerateReceipt
     */
    public GenerateReceipt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        appoi_id = new javax.swing.JTextField();
        recep_id = new javax.swing.JTextField();
        recepsionist_id = new javax.swing.JTextField();
        pay_sta = new javax.swing.JTextField();
        patient_id = new javax.swing.JTextField();
        room_doc = new javax.swing.JComboBox<>();
        generate_recp = new javax.swing.JButton();
        peint_recep = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backbtn.setText("<-");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Generate Receipt");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Appointment Id:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Receipt Id:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Patient Id:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Doctor Room no:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Pay Status:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Receptionist Id:");

        room_doc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        generate_recp.setBackground(new java.awt.Color(255, 255, 204));
        generate_recp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        generate_recp.setText("Generate Receipt");
        generate_recp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generate_recpActionPerformed(evt);
            }
        });

        peint_recep.setBackground(new java.awt.Color(255, 255, 204));
        peint_recep.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        peint_recep.setText("Print Receipt");
        peint_recep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peint_recepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(appoi_id, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(recep_id, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patient_id, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(pay_sta, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(recepsionist_id, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room_doc, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backbtn)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(generate_recp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(peint_recep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(backbtn))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(room_doc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(appoi_id, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(recep_id, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pay_sta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(patient_id, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(recepsionist_id, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(generate_recp)
                .addGap(18, 18, 18)
                .addComponent(peint_recep)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        new ReceptionistDashBoard().setVisible(true);
    }//GEN-LAST:event_backbtnActionPerformed

    private void generate_recpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generate_recpActionPerformed
        // TODO add your handling code here:
       pat_id=patient_id.getText();
           
     App_id=appoi_id.getText();
       Recp_id=recep_id.getText();
      Recpt_id=recepsionist_id.getText();
     room_no = Integer.parseInt(room_doc.getSelectedItem().toString());

      pay_status=pay_sta.getText();
     
        
    }//GEN-LAST:event_generate_recpActionPerformed

    private void peint_recepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peint_recepActionPerformed
        // TODO add your handling code here:
                 bHeight = (double) App_id.length();
                 JOptionPane.showMessageDialog(rootPane, bHeight);
                 PrinterJob pj=PrinterJob.getPrinterJob();
                 pj.setPrintable(new BillPrintable(),getPageFormat(pj));
                 try{
                     pj.print();
                 }
                 catch(PrinterException ex){
                     ex.printStackTrace();
                 }
    }//GEN-LAST:event_peint_recepActionPerformed

    public PageFormat getPageFormat(PrinterJob pj){
        PageFormat pf=pj.defaultPage();
        Paper paper=pf.getPaper();
        
        double bodyHeight=bHeight;
        double headerHeight=5.0;
        double footerHeight=5.0;
        double width=cm_to_pp(8);
        double height=cm_to_pp(headerHeight+bodyHeight+footerHeight);
        paper.setSize(width,height);
        paper.setImageableArea(0,10,width, height-cm_to_pp(1));
        
        pf.setOrientation(PageFormat.PORTRAIT);
        pf.setPaper(paper);
        return pf;
        
    }
    public static double cm_to_pp(double cm){
        return toPPI(cm*0.393600787);
        
    }
    public static double toPPI(double inch){
        return inch*72d;
    }
//    public PageFormat getPageFormat(PrinterJob pj) {
//    PageFormat pf = pj.defaultPage();
//    Paper paper = pf.getPaper();
//
//    // Define fixed dimensions for a medium-sized receipt
//    double receiptWidth = cm_to_pp(8);  // Width of the receipt in cm (e.g., 8cm)
//    double receiptHeight = cm_to_pp(20); // Height of the receipt in cm (e.g., 20cm)
//
//    paper.setSize(receiptWidth, receiptHeight);
//    paper.setImageableArea(10, 10, receiptWidth - 20, receiptHeight - 20); // Margins
//
//    pf.setOrientation(PageFormat.PORTRAIT);
//    pf.setPaper(paper);
//    return pf;
//}

   public class BillPrintable implements Printable {

    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex)
            throws PrinterException {

        int result = NO_SUCH_PAGE;

        if (pageIndex == 0) {
            Graphics2D g2d = (Graphics2D) graphics;
            g2d.translate((int) pageFormat.getImageableX(), (int) pageFormat.getImageableY());

            // Header and Clinic Details
            try {
                int y = 20;
                int yShift = 10;
                int headerRectHeight = 15;

                g2d.setFont(new Font("Monospaced", Font.PLAIN, 10));
                g2d.drawImage(new ImageIcon("D:\\4semester\\final-sems-pro-SC\\src\\main\\java\\applogo.jpg").getImage(), 50, 20, 90, 30, rootPane);
                y += yShift + 30;
                g2d.drawString("--------------------------", 12, y);
                y += yShift;
                g2d.drawString("Clinic Management System", 12, y);
                y += yShift;
                g2d.drawString("Address: Rawalpindi, Pakistan", 12, y);
                y += yShift;
                g2d.drawString("Phone: +92300000000", 12, y);
                y += yShift;
                g2d.drawString("Email: contact:eishasajid316@gmail.com", 12, y);
                y += yShift;
                g2d.drawString("--------------------------", 12, y);
                y += headerRectHeight;

                // Display IDs in the Header
                g2d.drawString("Patient ID: " + pat_id, 10, y);
                y += yShift;
                g2d.drawString("Appointment ID: " + App_id, 10, y);
                y += yShift;
                g2d.drawString("Receipt ID: " + Recpt_id, 10, y);
                y += yShift;
                g2d.drawString("Receptionist ID: " + Recp_id, 10, y);
                y += yShift;
                g2d.drawString("Doctor Room No: " + room_no, 10, y);
                y += yShift;
                g2d.drawString("Payment Status: " + pay_status, 10, y);
                y += yShift;
                g2d.drawString("--------------------------", 10, y);
                y += headerRectHeight;

                // Leave Body Empty for Doctor's Prescription
                g2d.drawString("Prescription Area:", 10, y);
                y += yShift + 10;
                g2d.drawRect(10, y, 200, 100); // Empty space for the doctor to fill prescription manually
                y += 110;

                // Footer
                g2d.drawString("--------------------------", 10, y);
                y += yShift;
                g2d.drawString("THANK YOU!", 10, y);
                y += yShift;
                g2d.drawString("Software by E & A", 10, y);
                y += yShift;

            } catch (Exception e) {
                e.printStackTrace();
            }

            result = PAGE_EXISTS;
        }
        return result;
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerateReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerateReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerateReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerateReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerateReceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField appoi_id;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton generate_recp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField patient_id;
    private javax.swing.JTextField pay_sta;
    private javax.swing.JButton peint_recep;
    private javax.swing.JTextField recep_id;
    private javax.swing.JTextField recepsionist_id;
    private javax.swing.JComboBox<String> room_doc;
    // End of variables declaration//GEN-END:variables
}
