
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author EISHA
 */
public class ManageDoctor extends javax.swing.JFrame {
 String name,gender,spec,doctorID,ph_number,pass,conf_pass,role;
          int exp,room_no;
          long number;
    /**
     * Creates new form ManageDoctor
     */
    public ManageDoctor() {
        initComponents();
        scaleImage();
    }
     public void scaleImage() {
        ImageIcon icon = new ImageIcon("C:\\Users\\EISHA\\Desktop\\patientbackk.jpeg");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(back_img_label.getWidth(), back_img_label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        back_img_label.setIcon(scaledIcon);

    }
    private void clearFields() {
    doc_name.setText("");       // Clear the ID field
  doc_gen.setText("");      // Clear the password field
    doc_spec.setText("");
    doc_id.setText("");
    doc_exp.setText("");
    doc_room.setText("");
     doc_phone.setText("");
    doc_role.setText("");
     doc_pass.setText("");
     doc_conf_pass.setText("");
     

// Clear the role field
}
    public boolean ValidateInputs() {
    // Validate Name, Gender, Specialty, Doctor ID (non-empty strings)
    if (name == null || name.trim().isEmpty() || 
        gender == null || gender.trim().isEmpty() || 
        spec == null || spec.trim().isEmpty() || 
        doctorID == null || doctorID.trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "All fields (Name, Gender, Specialty, Doctor ID) are required.");
        return false;
    }
 if (role.isEmpty() || !(role.equalsIgnoreCase("doctor")) )
    {
        JOptionPane.showMessageDialog(null, "Role must be either 'doctor'.");
        return false;
    }
    // Validate Phone Number (non-empty and numeric)
    if (ph_number == null || ph_number.trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Phone number cannot be empty.");
        return false;
    }
    try {
        number = Long.parseLong(ph_number);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Phone number must be a valid number.");
        return false;
    }

    // Validate Password (non-empty)
    if (pass == null || pass.trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Password cannot be empty.");
        return false;
    }

    // Validate Confirm Password (non-empty and matches password)
    if (conf_pass == null || conf_pass.trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Confirm password cannot be empty.");
        return false;
    }
    if (!pass.equals(conf_pass)) {
        JOptionPane.showMessageDialog(null, "Passwords do not match.");
        return false;
    }

    // Validate Experience (numeric and valid)
    if (exp <= 0) {
        JOptionPane.showMessageDialog(null, "Experience must be a positive number.");
        return false;
    }

    // Validate Room Number (numeric and valid)
    if (room_no <= 0) {
        JOptionPane.showMessageDialog(null, "Room number must be a positive number.");
        return false;
    }

    // All validations passed
    return true;
}

   
public void getValues(){
    
    name=doc_name.getText();
    gender=doc_gen.getText();
    spec=doc_spec.getText();
    doctorID=doc_id.getText();
    ph_number=doc_phone.getText();
    number=Long.parseLong(ph_number);
    role=doc_role.getText();
      pass = new String(doc_pass.getPassword());
      conf_pass=new String(doc_conf_pass.getPassword());
     try {
           exp = Integer.parseInt(doc_exp.getText());
     } catch (NumberFormatException e)
     {
    // Handle the error, e.g., show a message to the user
             JOptionPane.showMessageDialog(null, "Enter Exp in numbers.");
        }
 try {
           room_no=Integer.parseInt(doc_room.getText());
     } catch (NumberFormatException e)
     {
    // Handle the error, e.g., show a message to the user
             JOptionPane.showMessageDialog(null, "Enter Valid Room no (in numbers).");
        }
    
}
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        doc_conf_pass = new javax.swing.JPasswordField();
        doc_pass = new javax.swing.JPasswordField();
        doc_name = new javax.swing.JTextField();
        doc_phone = new javax.swing.JTextField();
        doc_gen = new javax.swing.JTextField();
        doc_spec = new javax.swing.JTextField();
        doc_exp = new javax.swing.JTextField();
        doc_id = new javax.swing.JTextField();
        doc_room = new javax.swing.JTextField();
        doc_role = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSearchAll = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        back_img_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Manage Doctor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 23, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("<-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 23, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 104, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Doctor ID:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 194, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Experience:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 104, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Doctor Room no:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 194, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Gender:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 104, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Password:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 194, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Phone no:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 104, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Confirm Password:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 194, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Specialization:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(738, 104, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Role:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(738, 194, -1, -1));
        getContentPane().add(doc_conf_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 220, 100, 25));
        getContentPane().add(doc_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 220, 100, 25));
        getContentPane().add(doc_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 126, 100, 25));
        getContentPane().add(doc_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 126, 100, 25));
        getContentPane().add(doc_gen, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 126, 100, 25));
        getContentPane().add(doc_spec, new org.netbeans.lib.awtextra.AbsoluteConstraints(738, 126, 100, 25));
        getContentPane().add(doc_exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 126, 100, 25));
        getContentPane().add(doc_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 220, 100, 25));
        getContentPane().add(doc_room, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 220, 100, 25));
        getContentPane().add(doc_role, new org.netbeans.lib.awtextra.AbsoluteConstraints(738, 220, 100, 25));

        btnAdd.setBackground(new java.awt.Color(255, 255, 204));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 272, 100, 40));

        btnUpdate.setBackground(new java.awt.Color(255, 255, 204));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 272, 100, 40));

        btnDelete.setBackground(new java.awt.Color(255, 255, 204));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 272, 100, 40));

        btnSearchAll.setBackground(new java.awt.Color(204, 204, 204));
        btnSearchAll.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearchAll.setText("SEARCH ALL");
        btnSearchAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAllActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearchAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 330, 200, -1));

        btnSearch.setBackground(new java.awt.Color(255, 255, 204));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 272, 100, 40));
        getContentPane().add(back_img_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 0, 870, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        getValues();
        if(true){
            Doctor doct=new Doctor(doctorID,name,exp,room_no,gender,number,spec,role,pass);
            
            doct.AddToDB();
            clearFields();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
         getValues();
        if(true){
            Doctor doct1=new Doctor(doctorID,name,exp,room_no,gender,number,spec,role,pass);
            
            doct1.UpdateDb();
            clearFields();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String doctors_id=doc_id.getText();
        if(doctors_id.isEmpty()){
            JOptionPane.showMessageDialog(null,"Id is reuired for deleting");
        }
        else{
            Doctor doctor1=new Doctor();
              doctor1.Delete(doctors_id);
              clearFields();
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
         String doctors_id=doc_id.getText();
          if(doctors_id.isEmpty()){
            JOptionPane.showMessageDialog(null,"Id is reuired for deleting");
        }
        else{
               Doctor doctor1=new Doctor();
               doctor1.Search(doctors_id);
               clearFields();
          }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSearchAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAllActionPerformed
        // TODO add your handling code here:
        Doctor doctor1=new Doctor();
               doctor1.SearchAllDoctors();
    }//GEN-LAST:event_btnSearchAllActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AdminInterface().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back_img_label;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearchAll;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPasswordField doc_conf_pass;
    private javax.swing.JTextField doc_exp;
    private javax.swing.JTextField doc_gen;
    private javax.swing.JTextField doc_id;
    private javax.swing.JTextField doc_name;
    private javax.swing.JPasswordField doc_pass;
    private javax.swing.JTextField doc_phone;
    private javax.swing.JTextField doc_role;
    private javax.swing.JTextField doc_room;
    private javax.swing.JTextField doc_spec;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
