
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author EISHA
 */
public class ManageAdmin extends javax.swing.JFrame {

    String name, gender, pass, conf_pass, email, role, add_id, ph_no;
    long phone;

    /**
     * Creates new form ManAdmin
     */
    public ManageAdmin() {
        initComponents();
//        note.setEditable(false);
        scaleImage();

    }
 public void scaleImage(){
       ImageIcon icon=new ImageIcon("C:\\Users\\EISHA\\Desktop\\doctorrback.jpg");
       Image img=icon.getImage();
       Image imgScale=img.getScaledInstance(back_img_label.getWidth(),back_img_label.getHeight(),Image.SCALE_SMOOTH);
       ImageIcon scaledIcon=new ImageIcon(imgScale);
       back_img_label.setIcon(scaledIcon);
       
       
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        admin_gen = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        admin_name = new javax.swing.JTextField();
        admin_id = new javax.swing.JTextField();
        ad_role = new javax.swing.JTextField();
        ad_gen = new javax.swing.JTextField();
        admin_num = new javax.swing.JTextField();
        add_email = new javax.swing.JTextField();
        admin_conf_pass = new javax.swing.JPasswordField();
        admin_pass = new javax.swing.JPasswordField();
        btnSearch = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        back_img_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Manage Admin");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Phone #:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Admin Id:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Confirm Password:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Password:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        admin_gen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        admin_gen.setText("Gender:");
        getContentPane().add(admin_gen, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Role:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Email:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));
        getContentPane().add(admin_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 130, 40));
        getContentPane().add(admin_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 130, 40));
        getContentPane().add(ad_role, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 130, 40));
        getContentPane().add(ad_gen, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 130, 40));
        getContentPane().add(admin_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 130, 40));
        getContentPane().add(add_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 130, 40));
        getContentPane().add(admin_conf_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 130, 40));
        getContentPane().add(admin_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 130, 40));

        btnSearch.setBackground(new java.awt.Color(255, 255, 204));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 130, 40));

        btnAdd.setBackground(new java.awt.Color(255, 255, 204));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 130, 40));

        btnUpdate.setBackground(new java.awt.Color(255, 255, 204));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 130, 40));

        btnDelete.setBackground(new java.awt.Color(255, 255, 204));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 130, 40));

        btnBack.setBackground(new java.awt.Color(255, 0, 0));
        btnBack.setText("<-");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        getContentPane().add(back_img_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 660, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

  
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String add_id = admin_id.getText();

        // Validate input
        if (add_id.isEmpty()) {
            JOptionPane.showMessageDialog(null, "AdminId is required to search.");

        }

             else {
                Admin adam=new Admin();
                adam.Search(add_id);
            }
       
        
    }//GEN-LAST:event_btnSearchActionPerformed

    public boolean ValidateInputAll() {
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Name cannot be empty.");
            return false;
        }
        if (gender.isEmpty() || !(gender.equalsIgnoreCase("M") || gender.equalsIgnoreCase("F"))) {
            JOptionPane.showMessageDialog(null, "Please enter a valid gender (M for Male,F for Female).");
            return false;
        }

        if (String.valueOf(ph_no).length() != 10) {
            JOptionPane.showMessageDialog(null, "Phone number must be 10 digits and numeric.");
            return false;
        }
        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Email cannot be empty.");
            return false;
        }
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
        Pattern pattern = Pattern.compile(emailRegex);
        Matcher matcher = pattern.matcher(email);
        if (!matcher.matches()) {
            JOptionPane.showMessageDialog(null, "Please enter a valid email address.");
            return false;
        }
        if (add_id.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Admin ID cannot be empty.");
            return false;
        }
        if (role.isEmpty() || !(role.equalsIgnoreCase("admin"))) {
            JOptionPane.showMessageDialog(null, "Role must be either 'admin'.");
            return false;
        }
        if (!pass.equals(conf_pass)) {
            JOptionPane.showMessageDialog(null, "Passwords do not match.");
            return false;
        }
        if (pass.isEmpty() || pass.length() < 6) {
            JOptionPane.showMessageDialog(null, "Password must be at least 6 characters long.");
            return false;
        }

        return true;
    }

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AdminInterface().setVisible(true);

    }//GEN-LAST:event_btnBackActionPerformed

    public void getInputs() {

        name = admin_name.getText();
        gender = ad_gen.getText();
        conf_pass = new String(admin_conf_pass.getPassword());
        role = ad_role.getText();
        ph_no = admin_num.getText();
        phone = Long.parseLong(ph_no);
        email = add_email.getText();
        add_id = admin_id.getText();
        pass = new String(admin_pass.getPassword());
    }
  private void clearFields() {
    admin_id.setText("");       // Clear the ID field
  admin_pass.setText("");      // Clear the password field
    ad_role.setText("");
    admin_name.setText("");
    
     ad_gen.setText("");
     admin_conf_pass.setText("");
     admin_num.setText("");
     add_email.setText("");
     

// Clear the role field
}
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        getInputs();

        if (ValidateInputAll()) {
            // Establish database connection
            Admin ad1 = new Admin(add_id, name, gender, phone, role, email, pass);

            ad1.Add();
            clearFields();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        getInputs();
        // Validate the input fields
        if (ValidateInputAll()) {
            // Establish database connection
            Admin ad2 = new Admin(add_id, name, gender, phone, role, email, pass);
            ad2.Upadte();
             clearFields();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        add_id = admin_id.getText();
        // Validate input
        if (add_id.isEmpty()) {
            JOptionPane.showMessageDialog(null, "AdminId is required to delete the record.");

        } else
        {
            Admin ad3=new Admin(add_id,name,gender,phone,role,email,pass);
      ad3.Delete();
       clearFields();
    }//GEN-LAST:event_btnDeleteActionPerformed
    }    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad_gen;
    private javax.swing.JTextField ad_role;
    private javax.swing.JTextField add_email;
    private javax.swing.JPasswordField admin_conf_pass;
    private javax.swing.JLabel admin_gen;
    private javax.swing.JTextField admin_id;
    private javax.swing.JTextField admin_name;
    private javax.swing.JTextField admin_num;
    private javax.swing.JPasswordField admin_pass;
    private javax.swing.JLabel back_img_label;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
