/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author EISHA
 */
public class ManagePatient extends javax.swing.JFrame {

    /**
     * Creates new form ManagePatient
     */
    public ManagePatient() {
        initComponents();
        notes_below.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        pat_id = new javax.swing.JTextField();
        phone_no = new javax.swing.JTextField();
        emerg_no = new javax.swing.JTextField();
        gender = new javax.swing.JTextField();
        pat_name = new javax.swing.JTextField();
        add_patient = new javax.swing.JButton();
        delete_patient = new javax.swing.JButton();
        search_patient = new javax.swing.JButton();
        update_patient = new javax.swing.JButton();
        textnotes = new javax.swing.JScrollPane();
        notes_below = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Manage Patient");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 6, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Patient ID(CNIC):");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 99, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 188, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Gender:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 99, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Phone #:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 99, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Emergency Contact:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 188, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Age:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 188, -1, -1));
        getContentPane().add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 214, 140, 35));
        getContentPane().add(pat_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 122, 140, 35));
        getContentPane().add(phone_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 122, 140, 35));
        getContentPane().add(emerg_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 214, 140, 35));
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 122, 140, 35));
        getContentPane().add(pat_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 214, 140, 35));

        add_patient.setBackground(new java.awt.Color(255, 255, 204));
        add_patient.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        add_patient.setText("ADD");
        getContentPane().add(add_patient, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 279, 100, 40));

        delete_patient.setBackground(new java.awt.Color(255, 255, 204));
        delete_patient.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        delete_patient.setText("DELETE");
        delete_patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_patientActionPerformed(evt);
            }
        });
        getContentPane().add(delete_patient, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 279, 100, 40));

        search_patient.setBackground(new java.awt.Color(255, 255, 204));
        search_patient.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        search_patient.setText("SEARCH");
        getContentPane().add(search_patient, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 279, 100, 40));

        update_patient.setBackground(new java.awt.Color(255, 255, 204));
        update_patient.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        update_patient.setText("UPDATE");
        getContentPane().add(update_patient, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 279, 100, 40));

        notes_below.setColumns(20);
        notes_below.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        notes_below.setForeground(new java.awt.Color(255, 51, 51));
        notes_below.setRows(5);
        notes_below.setText("For Delete and Search only Patient ID is required:\nFor Add and Update All input fields are Mandatory.\n");
        textnotes.setViewportView(notes_below);

        getContentPane().add(textnotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 463, 62));

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\4semester\\final-sems-pro-SC\\src\\main\\java\\icon\\back2.jpg")); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 750, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delete_patientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_patientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_patientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagePatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_patient;
    private javax.swing.JTextField age;
    private javax.swing.JButton delete_patient;
    private javax.swing.JTextField emerg_no;
    private javax.swing.JTextField gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextArea notes_below;
    private javax.swing.JTextField pat_id;
    private javax.swing.JTextField pat_name;
    private javax.swing.JTextField phone_no;
    private javax.swing.JButton search_patient;
    private javax.swing.JScrollPane textnotes;
    private javax.swing.JButton update_patient;
    // End of variables declaration//GEN-END:variables
}
