/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author EISHA
 */
public class ReceptionistInterface extends javax.swing.JFrame {

    /**
     * Creates new form ReceptionistInterface
     */
    public ReceptionistInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        GenRec = new javax.swing.JButton();
        ManDoc = new javax.swing.JButton();
        SchdApp = new javax.swing.JButton();
        ManPat = new javax.swing.JButton();
        RecName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 153));
        jLabel2.setText("Receptionist DashBoard");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        GenRec.setBackground(new java.awt.Color(255, 255, 204));
        GenRec.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GenRec.setText("Generate Receipt");
        GenRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenRecActionPerformed(evt);
            }
        });
        getContentPane().add(GenRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 190, 70));

        ManDoc.setBackground(new java.awt.Color(255, 255, 204));
        ManDoc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ManDoc.setText("Manage Doctors");
        ManDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManDocActionPerformed(evt);
            }
        });
        getContentPane().add(ManDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 190, 70));

        SchdApp.setBackground(new java.awt.Color(255, 255, 204));
        SchdApp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SchdApp.setText("Schedule Appointment");
        SchdApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SchdAppActionPerformed(evt);
            }
        });
        getContentPane().add(SchdApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 190, 70));

        ManPat.setBackground(new java.awt.Color(255, 255, 204));
        ManPat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ManPat.setText("Manage Patients");
        ManPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManPatActionPerformed(evt);
            }
        });
        getContentPane().add(ManPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 190, 70));

        RecName.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        RecName.setForeground(new java.awt.Color(0, 51, 51));
        RecName.setText("Receptionist Name");
        getContentPane().add(RecName, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 26, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SchdAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SchdAppActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ScheduleApp().setVisible(false);
        
    }//GEN-LAST:event_SchdAppActionPerformed

    private void ManPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManPatActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ManagePatient().setVisible(true);
    }//GEN-LAST:event_ManPatActionPerformed

    private void GenRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenRecActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new GenerateReceipt().setVisible(true);
    }//GEN-LAST:event_GenRecActionPerformed

    private void ManDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManDocActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ManageDoctor().setVisible(true);
    }//GEN-LAST:event_ManDocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceptionistInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceptionistInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceptionistInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceptionistInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceptionistInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GenRec;
    private javax.swing.JButton ManDoc;
    private javax.swing.JButton ManPat;
    private javax.swing.JLabel RecName;
    private javax.swing.JButton SchdApp;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
