/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author EISHA
 */
import javax.swing.JOptionPane;
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        RegLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        regemail = new javax.swing.JTextField();
        role = new javax.swing.JTextField();
        phoneno = new javax.swing.JTextField();
        RegName = new javax.swing.JTextField();
        regconfpass = new javax.swing.JPasswordField();
        regpass = new javax.swing.JPasswordField();
        register = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Registration");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        RegLogin.setBackground(new java.awt.Color(204, 255, 204));
        RegLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RegLogin.setText("Already have an account?");
        RegLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        RegLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegLoginActionPerformed(evt);
            }
        });
        getContentPane().add(RegLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, -1, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setText("Phone no");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setText("Role");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 204));
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setText("Confirm Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 204));
        jLabel8.setText("Name");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 204));
        jLabel9.setText("email");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        regemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regemailActionPerformed(evt);
            }
        });
        getContentPane().add(regemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 130, 30));
        getContentPane().add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 130, 30));
        getContentPane().add(phoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 130, 30));
        getContentPane().add(RegName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 130, 30));
        getContentPane().add(regconfpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 130, 30));
        getContentPane().add(regpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 130, 30));

        register.setBackground(new java.awt.Color(255, 255, 204));
        register.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        getContentPane().add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 130, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\EISHA\\Desktop\\and-healthcare\\and-healthcare\\back2.jpg")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 580, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegLoginActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new LoginForm().setVisible(true);
        
        
    }//GEN-LAST:event_RegLoginActionPerformed

    private void regemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regemailActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
              String name=RegName.getText();
              String email=regemail.getText();
           String reg_role=role.getText();
         String phone_no = phoneno.getText();
long phone = 0;
     
           String password = new String(regpass.getPassword());
String confirm_password = new String(regconfpass.getPassword());
              boolean isValid = true;

// Check for empty fields
if (name.isEmpty() || email.isEmpty() || reg_role.isEmpty() || phone_no.isEmpty() || password.isEmpty() || confirm_password.isEmpty()) {
    isValid = false;
    JOptionPane.showMessageDialog(null, "Please fill in all fields.", "Validation Error", JOptionPane.ERROR_MESSAGE);
}
if (reg_role.equalsIgnoreCase("doctor") || 
    reg_role.equalsIgnoreCase("admin") || 
    reg_role.equalsIgnoreCase("receptionist")) {
    isValid=true;
}else{
    JOptionPane.showMessageDialog(null, "Role must be Doctor,Admin or Receptionist", "Validation Error", JOptionPane.ERROR_MESSAGE);
       
    isValid=false;
}
 if (isValid) {
    try {
        phone = Long.parseLong(phone_no);
        if (phone_no.length() != 11) {
            isValid = false;
            JOptionPane.showMessageDialog(null, "Phone number must be 10 digits.", "Validation Error", JOptionPane.ERROR_MESSAGE);
       
        }
    } catch (NumberFormatException e) {
        isValid = false;
        JOptionPane.showMessageDialog(null, "Phone number must contain only digits.", "Validation Error", JOptionPane.ERROR_MESSAGE);
    }
}
 // Validate email format (basic regex check)
if (isValid && !email.matches("^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$")) {
    isValid = false;
    JOptionPane.showMessageDialog(null, "Invalid email format.", "Validation Error", JOptionPane.ERROR_MESSAGE);
}
if (isValid && !password.equals(confirm_password)) {
    isValid = false;
    JOptionPane.showMessageDialog(null, "Password and confirm password do not match.", "Validation Error", JOptionPane.ERROR_MESSAGE);
}
if (isValid) {
    
       Authentication registerNewUser=new Authentication();
                registerNewUser.register(name, email, reg_role, phone, password);
    
} else {
    JOptionPane.showMessageDialog(null, "Registration failed due to validation errors.", "Failure", JOptionPane.ERROR_MESSAGE);
}
        

        // TODO add your handling code here:
    }//GEN-LAST:event_registerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegLogin;
    private javax.swing.JTextField RegName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField phoneno;
    private javax.swing.JPasswordField regconfpass;
    private javax.swing.JTextField regemail;
    private javax.swing.JButton register;
    private javax.swing.JPasswordField regpass;
    private javax.swing.JTextField role;
    // End of variables declaration//GEN-END:variables
}
