
import java.awt.HeadlessException;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import java.util.Date; // For working with date and time
import java.text.SimpleDateFormat; // For formatting the date/time as needed
import java.util.ArrayList;
import javax.swing.JOptionPane; // For showing dialog boxes

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author EISHA
 */
public class ScheduleApp extends javax.swing.JFrame {
    String ap_id,d_id,p_id,a_time;
    Date ap_date;
  
    Doctor doctor;
    

    /**
     * Creates new form ScheduleApp
     */
    public ScheduleApp() {
        initComponents();
        pay_method.setText("Card");
        pay_method.setEditable(false);
        amount.setText("Rs:2000");
        amount.setEditable(false);
        notes.setEditable(false);
        loadDoctor();
        loadPatient();
    }
public void getInputs() {
    // Fetch the selected time from the time picker (assuming it's a JSpinner or JDateChooser)
    Object selectedTime = app_time.getValue();
    if (selectedTime != null)
    {
        if (selectedTime instanceof Date) {
            // Format the selected time to HH:mm
            SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm");
            a_time = timeFormat.format((Date) selectedTime);  // Format and assign to a_time
        } else {
            // Handle case where time is not in the expected format
            JOptionPane.showMessageDialog(null, "Invalid time format selected.");
            return;  // Exit if time format is invalid
        }
    } else {
        // Handle case where no time is selected
        JOptionPane.showMessageDialog(null, "Please select a valid time.");
        return;  // Exit if no time is selected
    }

    // Collect the other input fields
    ap_id = app_id.getText();  // Appointment ID from text field
    ap_date = appDate.getDate();  // Appointment date from date picker
    d_id = (String) doc_id.getSelectedItem();  // Doctor ID from combo box
    p_id = (String) pat_id.getSelectedItem();  // Patient ID from combo box

    // Optional: Display the gathered inputs for debugging
    System.out.println("Appointment ID: " + ap_id);
    System.out.println("Appointment Date: " + ap_date);
    System.out.println("Doctor ID: " + d_id);
    System.out.println("Patient ID: " + p_id);
    System.out.println("Appointment Time: " + a_time);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        app_id = new javax.swing.JTextField();
        appDate = new com.toedter.calendar.JDateChooser();
        Add = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        doc_id = new javax.swing.JComboBox<>();
        pat_id = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        process_payment = new javax.swing.JButton();
        amount = new javax.swing.JTextField();
        card_no = new javax.swing.JTextField();
        card_holder = new javax.swing.JTextField();
        cvv = new javax.swing.JTextField();
        pay_id = new javax.swing.JTextField();
        pay_method = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        notes = new javax.swing.JTextArea();
        backbtn = new javax.swing.JButton();
        app_time = new javax.swing.JSpinner();
        SearchAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Appointment Id:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Doctor Id:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Patient Id:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Appointment Date:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Appointment Time:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 110, -1, -1));
        jPanel1.add(app_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 130, 40));
        jPanel1.add(appDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 130, 150, 40));

        Add.setBackground(new java.awt.Color(255, 255, 204));
        Add.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Add.setText("ADD");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jPanel1.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 100, 35));

        Delete.setBackground(new java.awt.Color(255, 255, 204));
        Delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Delete.setText("DELETE");
        jPanel1.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 100, 35));

        Search.setBackground(new java.awt.Color(255, 255, 204));
        Search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Search.setText("SEARCH");
        jPanel1.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 100, 35));

        Update.setBackground(new java.awt.Color(255, 255, 204));
        Update.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Update.setText("UPDATE");
        jPanel1.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 210, 100, 35));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Schedule Appointment");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 102));
        jLabel7.setText("Payment Details");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 360, 45));

        doc_id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        doc_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_idActionPerformed(evt);
            }
        });
        jPanel1.add(doc_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 130, 40));

        pat_id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pat_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pat_idActionPerformed(evt);
            }
        });
        jPanel1.add(pat_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 130, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Amount:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 400, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 317, 1200, 10));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Pay Id:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Card no:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("CVV:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Pay method:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Card Holder Name:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 400, -1, -1));

        process_payment.setBackground(new java.awt.Color(255, 255, 204));
        process_payment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        process_payment.setText("Pay Now");
        process_payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                process_paymentActionPerformed(evt);
            }
        });
        jPanel1.add(process_payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, 100, 40));
        jPanel1.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 420, 130, 40));
        jPanel1.add(card_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 130, 40));
        jPanel1.add(card_holder, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 420, 130, 40));
        jPanel1.add(cvv, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 130, 40));
        jPanel1.add(pay_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 130, 40));
        jPanel1.add(pay_method, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 130, 40));

        notes.setEditable(false);
        notes.setBackground(new java.awt.Color(204, 255, 204));
        notes.setColumns(20);
        notes.setForeground(new java.awt.Color(255, 0, 0));
        notes.setRows(5);
        notes.setText("For Add and Update all input fields are mandatory.\nFor Delete and Search only Patient Id is required");
        jScrollPane1.setViewportView(notes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 760, 40));

        backbtn.setBackground(new java.awt.Color(255, 51, 51));
        backbtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        backbtn.setText("<-");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        jPanel1.add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));
        jPanel1.add(app_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 130, 150, 40));
        SpinnerDateModel timeModel = new SpinnerDateModel();
        app_time.setModel(timeModel);
        app_time.setEditor(new JSpinner.DateEditor(app_time, "HH:mm")); // Set format to HH:mm

        SearchAll.setBackground(new java.awt.Color(255, 255, 204));
        SearchAll.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SearchAll.setText("SearchAll");
        jPanel1.add(SearchAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 210, 100, 35));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1210, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doc_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_idActionPerformed
        // TODO add your handling code here:
       

        
    }//GEN-LAST:event_doc_idActionPerformed

    public void loadDoctor(){
         try{ 
      Doctor doct=new Doctor();
      ArrayList<String> doctorDetails = doct.getDoctorList();

        // Clear existing items in the JComboBox
        doc_id.removeAllItems();

        // Populate the JComboBox with doctor names
        for (String name : doctorDetails) {
            doc_id.addItem(name);
        }

       
    } catch (HeadlessException e) {
        JOptionPane.showMessageDialog(this, "Error loading doctors: " + e.getMessage());
    }
    }
     public void loadPatient(){
         try{ 
      Patient pat=new Patient();
             ArrayList<String> PatientDetails = pat.getPatientList();

        // Clear existing items in the JComboBox
        pat_id.removeAllItems();

        // Populate the JComboBox with doctor names
        for (String name : PatientDetails) {
            pat_id.addItem(name);
        }

       
    } catch (HeadlessException e) {
        JOptionPane.showMessageDialog(this, "Error loading doctors: " + e.getMessage());
    }
    }
    private void pat_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pat_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pat_idActionPerformed

    private void process_paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_process_paymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_process_paymentActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        new ReceptionistDashBoard().setVisible(true);
    }//GEN-LAST:event_backbtnActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        getInputs();
       Appointment app=new Appointment(ap_id,d_id,p_id,ap_date,a_time);
    // Display the selected time
    app.Add();
  
        
    }//GEN-LAST:event_AddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScheduleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScheduleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScheduleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScheduleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScheduleApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Search;
    private javax.swing.JButton SearchAll;
    private javax.swing.JButton Update;
    private javax.swing.JTextField amount;
    private com.toedter.calendar.JDateChooser appDate;
    private javax.swing.JTextField app_id;
    private javax.swing.JSpinner app_time;
    private javax.swing.JButton backbtn;
    private javax.swing.JTextField card_holder;
    private javax.swing.JTextField card_no;
    private javax.swing.JTextField cvv;
    private javax.swing.JComboBox<String> doc_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea notes;
    private javax.swing.JComboBox<String> pat_id;
    private javax.swing.JTextField pay_id;
    private javax.swing.JTextField pay_method;
    private javax.swing.JButton process_payment;
    // End of variables declaration//GEN-END:variables
}
