
import java.awt.HeadlessException;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import java.util.Date; // For working with date and time
import java.text.SimpleDateFormat; // For formatting the date/time as needed
import java.util.ArrayList;
import javax.swing.JOptionPane; // For showing dialog boxes

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author EISHA
 */
public class ScheduleApp extends javax.swing.JFrame {
    String ap_id,a_time;
    Date ap_date;
    Doctor doctor;

    /**
     * Creates new form ScheduleApp
     */
    public ScheduleApp() {
        initComponents();
        pay_method.setText("Card");
        pay_method.setEditable(false);
        amount.setText("Rs:2000");
        amount.setEditable(false);
        notes.setEditable(false);
        loadDoctor();
        loadPatient();
    }
public void getInputs(){
      Date selectedTime = (Date) app_time.getValue();
    SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm");
    String formattedTime = timeFormat.format(selectedTime);
a_time=formattedTime;
ap_id=App_id.getText();
ap_date=appDate.getDate();

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        App_id = new javax.swing.JTextField();
        appDate = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        doc_avail = new javax.swing.JComboBox<>();
        pat_reg = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        process_payment = new javax.swing.JButton();
        amount = new javax.swing.JTextField();
        card_no = new javax.swing.JTextField();
        card_holder = new javax.swing.JTextField();
        cvv = new javax.swing.JTextField();
        pay_id = new javax.swing.JTextField();
        pay_method = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        notes = new javax.swing.JTextArea();
        backbtn = new javax.swing.JButton();
        app_time = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Appointment Id:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Doctor Id:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Patient Id:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Appointment Date:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Appointment Time:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 110, -1, -1));
        jPanel1.add(App_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 130, 40));
        jPanel1.add(appDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 130, 150, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 100, 35));

        jButton3.setBackground(new java.awt.Color(255, 255, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("DELETE");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 100, 35));

        jButton4.setBackground(new java.awt.Color(255, 255, 204));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("SEARCH");
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 100, 35));

        jButton2.setBackground(new java.awt.Color(255, 255, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("UPDATE");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 210, 100, 35));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Schedule Appointment");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 102));
        jLabel7.setText("Payment Details");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 360, 45));

        doc_avail.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        doc_avail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_availActionPerformed(evt);
            }
        });
        jPanel1.add(doc_avail, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 130, 40));

        pat_reg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pat_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pat_regActionPerformed(evt);
            }
        });
        jPanel1.add(pat_reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 130, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Amount:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 400, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 317, 1200, 10));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Pay Id:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Card no:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("CVV:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Pay method:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Card Holder Name:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 400, -1, -1));

        process_payment.setBackground(new java.awt.Color(255, 255, 204));
        process_payment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        process_payment.setText("Pay Now");
        process_payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                process_paymentActionPerformed(evt);
            }
        });
        jPanel1.add(process_payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, 100, 40));
        jPanel1.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 420, 130, 40));
        jPanel1.add(card_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 130, 40));
        jPanel1.add(card_holder, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 420, 130, 40));
        jPanel1.add(cvv, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 130, 40));
        jPanel1.add(pay_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 130, 40));
        jPanel1.add(pay_method, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 130, 40));

        notes.setEditable(false);
        notes.setBackground(new java.awt.Color(204, 255, 204));
        notes.setColumns(20);
        notes.setForeground(new java.awt.Color(255, 0, 0));
        notes.setRows(5);
        notes.setText("For Add and Update all input fields are mandatory.\nFor Delete and Search only Patient Id is required");
        jScrollPane1.setViewportView(notes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 760, 40));

        backbtn.setBackground(new java.awt.Color(255, 51, 51));
        backbtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        backbtn.setText("<-");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        jPanel1.add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));
        jPanel1.add(app_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 130, 150, 40));
        SpinnerDateModel timeModel = new SpinnerDateModel();
        app_time.setModel(timeModel);
        app_time.setEditor(new JSpinner.DateEditor(app_time, "HH:mm")); // Set format to HH:mm

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1210, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doc_availActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_availActionPerformed
        // TODO add your handling code here:
       

        
    }//GEN-LAST:event_doc_availActionPerformed

    public void loadDoctor(){
         try{ 
      Doctor doct=new Doctor();
      ArrayList<String> doctorDetails = doct.getDoctorList();

        // Clear existing items in the JComboBox
        doc_avail.removeAllItems();

        // Populate the JComboBox with doctor names
        for (String name : doctorDetails) {
            doc_avail.addItem(name);
        }

       
    } catch (HeadlessException e) {
        JOptionPane.showMessageDialog(this, "Error loading doctors: " + e.getMessage());
    }
    }
     public void loadPatient(){
         try{ 
      Patient pat=new Patient();
             ArrayList<String> PatientDetails = pat.getPatientList();

        // Clear existing items in the JComboBox
        pat_reg.removeAllItems();

        // Populate the JComboBox with doctor names
        for (String name : PatientDetails) {
            pat_reg.addItem(name);
        }

       
    } catch (HeadlessException e) {
        JOptionPane.showMessageDialog(this, "Error loading doctors: " + e.getMessage());
    }
    }
    private void pat_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pat_regActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pat_regActionPerformed

    private void process_paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_process_paymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_process_paymentActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        new ReceptionistInterface().setVisible(true);
    }//GEN-LAST:event_backbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
    // Display the selected time
  
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScheduleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScheduleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScheduleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScheduleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScheduleApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField App_id;
    private javax.swing.JTextField amount;
    private com.toedter.calendar.JDateChooser appDate;
    private javax.swing.JSpinner app_time;
    private javax.swing.JButton backbtn;
    private javax.swing.JTextField card_holder;
    private javax.swing.JTextField card_no;
    private javax.swing.JTextField cvv;
    private javax.swing.JComboBox<String> doc_avail;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea notes;
    private javax.swing.JComboBox<String> pat_reg;
    private javax.swing.JTextField pay_id;
    private javax.swing.JTextField pay_method;
    private javax.swing.JButton process_payment;
    // End of variables declaration//GEN-END:variables
}
